#!/bin/bash

#Reset de la connexion au lidar et à l'électron
sudo ifdown eth0
sudo ifdown wlan1
sudo ifup eth0
sudo ifup wlan1

sudo route delete default gw 0.0.0.0 eth0
sudo route delete default gw 0.0.0.0 wlan1
